version: v1.0.0-beta.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - npm install -g npm
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run release

